ClubeDoCarro/ClubeDoCarro/Areas/Proprietario/Models/Venda.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ClubeDoCarro.Areas.Proprietario.Models
{
    public class Venda
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int VendaId { get; set; }
        [Required]
        public int VeiculoId { get; set; }
        [Required]
        public int UsuarioVenda { get; set;  }
        [Required]
        public int UsuarioCompra { get; set; }
        [Required]
        public DateTime DataVenda { get; set; }
        [Required]
        public double ValorVenda { get; set; }
    }
}

ClubeDoCarro/ClubeDoCarro/Areas/Proprietario/Controllers/VeiculosController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ClubeDoCarro.Areas.Proprietario.Models;
using ClubeDoCarro.Models;

namespace ClubeDoCarro.Areas.Proprietario.Controllers
{
    public class VeiculosController : Controller
    {
        private ClubeDoCarroContext db = new ClubeDoCarroContext();

        // GET: Proprietario/Veiculos
        public ActionResult Index()
        {
            return View(db.Veiculos.ToList());
        }

        // GET: Proprietario/Veiculos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Veiculo veiculo = db.Veiculos.Find(id);
            if (veiculo == null)
            {
                return HttpNotFound();
            }
            return View(veiculo);
        }

        // GET: Proprietario/Veiculos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Proprietario/Veiculos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VeiculoID,Modelo,Marca,Cor,Placa,Ano,Complemento,Carroceria,Chassi,Preco,Km,Portas,Combustivel,DataAquisicao")] Veiculo veiculo)
        {
            if (ModelState.IsValid)
            {
                db.Veiculos.Add(veiculo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(veiculo);
        }

        // GET: Proprietario/Veiculos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Veiculo veiculo = db.Veiculos.Find(id);
            if (veiculo == null)
            {
                return HttpNotFound();
            }
            return View(veiculo);
        }

        // POST: Proprietario/Veiculos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VeiculoID,Modelo,Marca,Cor,Placa,Ano,Complemento,Carroceria,Chassi,Preco,Km,Portas,Combustivel,DataAquisicao")] Veiculo veiculo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(veiculo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(veiculo);
        }


        // GET: Proprietario/Veiculos/Venda/5
        public ActionResult DisponibilizaVenda(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Veiculo veiculo = db.Veiculos.Find(id);
            if (veiculo == null)
            {
                return HttpNotFound();
            }

              veiculo.DisponivelVenda = !veiculo.DisponivelVenda;

            if (ModelState.IsValid)
            {
                db.Entry(veiculo).State = EntityState.Modified;
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }


        // GET: Proprietario/Veiculos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Veiculo veiculo = db.Veiculos.Find(id);
            if (veiculo == null)
            {
                return HttpNotFound();
            }
            return View(veiculo);
        }

        // POST: Proprietario/Veiculos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Veiculo veiculo = db.Veiculos.Find(id);
            db.Veiculos.Remove(veiculo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClubeDoCarro/ClubeDoCarro/Areas/Proprietario/Controllers/VendasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClubeDoCarro.Areas.Proprietario.Models;
using ClubeDoCarro.Models;

namespace ClubeDoCarro.Areas.Proprietario.Controllers
{
    public class VendasController : Controller
    {
        private ClubeDoCarroContext db = new ClubeDoCarroContext();

        // GET: Proprietario/Vendas
        public ActionResult Index()
        {
            return View(db.Veiculos.ToList());
        }

        // GET: Proprietario/Vendas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Proprietario/Vendas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VendaId,VeiculoId,UsuarioVenda,UsuarioCompra,DataVenda,ValorVenda")] Venda venda)
        {
            if (ModelState.IsValid)
            {
                db.Vendas.Add(venda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(venda);
        }

    }
}

ClubeDoCarro/ClubeDoCarro/Areas/Proprietario/Views/Vendas/Create.cshtml
@model ClubeDoCarro.Areas.Proprietario.Models.Venda

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Venda</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.VeiculoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VeiculoId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VeiculoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UsuarioVenda, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UsuarioVenda, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UsuarioVenda, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UsuarioCompra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UsuarioCompra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UsuarioCompra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataVenda, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataVenda, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataVenda, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorVenda, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorVenda, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorVenda, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ClubeDoCarro/ClubeDoCarro/Areas/Proprietario/Views/Vendas/Index.cshtml
@model IEnumerable<ClubeDoCarro.Areas.Proprietario.Models.Veiculo>

@{
    ViewBag.Title = "Compra e Venda de Veículos";
}

<h2>Compra e Venda de Veículos</h2>
<br />
<h4>Veículos Disponíveis:</h4>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Modelo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Marca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Placa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ano)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Combustivel)
        </th>
        <th></th>
    </tr>
    
    @foreach (var item in Model)
    {
        if (item.DisponivelVenda)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Modelo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Marca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Placa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ano)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Preco)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Combustivel)
                </td>
                <td>
                    @Html.ActionLink("Detalhar", "Details", "Veiculos", new { id = item.VeiculoID }, new { }) |
                    @Html.ActionLink("Comprar", "Create", new { id = item.VeiculoID }) |
                    @Html.ActionLink("Vender", "Create", new { id = item.VeiculoID }) 
                </td>
            </tr>
        }
        
    }
</table>